name: Build dot env file
on:
  workflow_dispatch:

env:
  UPLOAD_DIR: "reports"

jobs:
  build-env:
    runs-on: ubuntu-latest
    environment: development-test-env

    strategy:
      matrix:
        service: [FE, BE]

    env:
      GITHUB__JSON_SECRETS: ${{ toJSON(secrets) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare env file for ${{ matrix.service }}
        env:
          SERVICE_PREFIX: ${{ matrix.service }}
          DOT_ENV_TEMPLATE: ${{ vars[format('{0}_DOT_ENV_FILE', matrix.service)] }}
        run: ./.github/scripts/prepare-env-file.sh

      - name: Upload env artifact (${{ matrix.service }})
        uses: actions/upload-artifact@v4
        with:
          name: env-${{ matrix.service }}
          path: ${{ env.UPLOAD_DIR }}
          overwrite: true
