name: Upload file
on:
  workflow_dispatch:
    inputs:
      upload-file:
        description: "Upload file?"
        required: true
        type: boolean
        default: false

env:
  UPLOAD_DIR: "reports"

jobs:
  upload-file:
    name: Database Migration & Report Upload
    # This ensures the job only runs if the user checked the 'migrate' box
    if: ${{ github.event.inputs.upload-file == 'true' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Create upload file
        run: |
          mkdir -p "${{ env.UPLOAD_DIR }}"
          echo "Migration report - $(date)" > "${{ env.UPLOAD_DIR }}/test.txt"

      - name: Upload scan reports
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: migration-reports
          path: ${{ env.UPLOAD_DIR }}
          overwrite: true
